### ISSUE TITLE
Add support for WebJob endpoints

### ISSUE THREAD

**Issue by benquarmby** [itsananderson/kudu-api#2]
Please consider adding support for the Kudu WebJob API endpoints:

https://github.com/projectkudu/kudu/wiki/WebJobs-API

**Comment by itsananderson** [comment]
Hi Ben. I'd love to add support for WebJobs, but I've been swamped and haven't had a chance. If I add you as a contributor to the project, would you be interested in adding this feature?

**Comment by benquarmby** [comment]
Yes, definitely. I'm reasonably swamped myself, but should be able to find some to implement it in the same style as the existing endpoints.

**Comment by benquarmby** [comment]
Work started here:
https://github.com/benquarmby/kudu-api/tree/webjobs

**Comment by itsananderson** [comment]
Awesome! I've added you as a contributor to the GitHub project and an owner on the npm package.

**Comment by benquarmby** [comment]
Published to https://www.npmjs.com/package/kudu-api
