### ISSUE TITLE
Issue with truncated downloads

### ISSUE THREAD

**Issue by jakkaj** [itsananderson/kudu-api#21]
Hi all, 

Have you guys had any issues with truncated ZIP downloads from Kudu?

I'm trying to track a zip extraction issue where the zips that come from kudu-api.zip.download cannot be extracted. It **may** be the unzipper is not working yet - the downloader may be working fine, I'm just hunting to see if you've seen this at all. 

Cheers.

**Comment by itsananderson** [comment]
I haven't seen that specifically. Do you know the size of the zip that's failing? That might help track down the issue.

If you can share the actual zip that's failing to download/unzip, that'd be even better, but obviously don't share it if it contains sensitive information 😃

**Comment by jakkaj** [comment]
Hey - so I'm using kudu.zip.download(dlUri, tmpFile.name, async (e)=>{

It's a brand new Azure Function, so very little content. 

The file is broken a lot of the time... but it works sometimes!

It's almost like the download didn't finish before the callback is called. 

I've tried on a few different App Service instances etc. 

[tmp-9872nEYxxX0wiZfB - Copy.zip](https://github.com/itsananderson/kudu-api/files/1129456/tmp-9872nEYxxX0wiZfB.-.Copy.zip)

**Comment by jakkaj** [comment]
Oh BTW, if I do a setTimeout of 5 seconds around before trying to extract the zip it mostly works.
