### ISSUE TITLE
JSON parsing exception after uploading file 

### ISSUE THREAD

**Issue by benquarmby** [itsananderson/kudu-api#3]
If a file is created using the `vfs.uploadFile` method, the exception "Unexpected end of input" will be thrown by kudu-api.

Note that this doesn't manifest if the uploaded file is a replacement rather than a creation.

I believe this is due to the fact that Kudu returns a `201 Created` response with an empty body the first time a file is uploaded. Subsequent calls will return a `204 No Content` response and be handled properly.

**Comment by itsananderson** [comment]
Fixed by #4
