### ISSUE TITLE
Unable to deploy WebApp using kudu rest api

### ISSUE THREAD

**Issue by Ajay-MS** [itsananderson/kudu-api#6]
I am trying to deploy web app using kudu api but not successful.

```
var kudu = require("kudu-api")({
    website: "DemoWebApp",
    username: "$DemoWebApp",
    password: "<Password>"
});

kudu.zip.upload("E:\\Work\\AzureWebApp1In.zip", "site\wwwroot", function(err) {
    if (err) throw err;
});
```

This script has been passed but on kudu server nothing has been deployed. Can you help what I have done wrong in above script. 

Can I deploy a webapp folder instead of zip too ?

**Comment by benquarmby** [comment]
@Ajay-MS: The third argument in that callback is the response object. I recommend interrogating the status code etc. to ensure it was actually successful.

FYI, the zip wrappers do currently return hard errors (cannot find file, DNS resolution etc.), but not HTTP errors (404 etc). The webjob wrappers do status code checking however, so if @itsananderson doesn't mind, I may go back and update them all to be consistent.

**Comment by benquarmby** [comment]
Also, I can see that slash in `site\wwwroot` needs to be escaped. I recommend switching to forward slashes.

**Comment by benquarmby** [comment]
I'm going to close this issue, since the HTTP error handling is being tracked in #7. Please re-open @Ajay-MS if there anything else you need help with.
